### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: 'makeblastdb'

### ISSUE THREAD

**Issue by fhdbqr** [aziele/phirbo#5]
Hi, I encountered an issue while running makeblastdb.py. Do you have any suggestions?
python makeblastdb.py --in /home/host --out out/db/
Traceback (most recent call last):
  File "/home/metagenome002/6_rep/virus_host/bastn/makeblastdb.py", line 44, in <module>
    subprocess.run(cmd)
  File "/home/metagenome002/miniconda3/envs/phirbo/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/metagenome002/miniconda3/envs/phirbo/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/metagenome002/miniconda3/envs/phirbo/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'makeblastdb'

**Comment by aziele** [comment]
Hi,

I tested the makeblastdb.py script with Python 3.12, and it worked fine on my system.

Could you please check if BLAST+ is installed on your system? You can do this by running the following command:

```
makeblastdb -version
```

This command will display the BLAST+ version information.

**Comment by fhdbqr** [comment]
Hi,thank you for your reply. I installed phirbo using conda, but there is no blast+ in the installation environment.
